device: 0
log_dir: logs

algorithm:
  name: fedavg
  # name: fedprox
  # name: scaffold

server:
  num_users: 10
  participation_rate: 1
  global_epochs: 200 # rounds
  save_interval: 10

client:
  train:
    local_epochs: 5
    batch_size: 128
    shuffle: True
    hyperparameter:
      mu: 1
  test:
    batch_size: 100
    shuffle: True

  optimizer:
    lr: 0.01
    momentum: 0.9
    weight_decay: 5e-4



dataset:
  heterogeneity:
    # beta: 0.1
    beta: 0.5
  train:
    transforms:
      - type: RandomCrop
        size: 32
        padding: 4
      - type: RandomHorizontalFlip
      - type: ToTensor
      - type: Normalize
        mean: [0.4914, 0.4822, 0.4465]
        std: [0.2023, 0.1994, 0.2010]
  test:
    transforms:
      - type: ToTensor
      - type: Normalize
        mean: [0.4914, 0.4822, 0.4465]
        std: [0.2023, 0.1994, 0.2010]